### PR TITLE
Fixed SessionName (requires doublequotes for names with spaces), added Mods, SaveFolder and ExtraParams for extra dash parameters.

### PR DESCRIPTION
**Pull request by simonghpub**

### CODE REVIEW

**Comment by patrix87** [comment]
I'm working on integrating those changes.

**Comment by patrix87** [comment]
I've modified your PR a bit, can you validate it on your side again.
It looked like it was working fine on my side.

**Comment by simonghpub** [comment]
Removal of the doublequotes for the SessionName makes the server ignore the specified port and listens on the default 7777 instead. 

```
SessionName            = "PowerShellGSM Ark Ascended Server"
"?SessionName=`"$($Server.SessionName)`"",
```
spaces_noquotes

```
SessionName            = "PowerShellGSM_NoSpacesHere"
"?SessionName=`"$($Server.SessionName)`"",
```
nospaces_noquotes

```
SessionName            = "PowerShellGSM Ark Ascended Server"
"?SessionName=`"`"`"$($Server.SessionName)`"`"`"",
```
spaces_withquotes


The rest seems fine :)

**Comment by patrix87** [comment]
Oh thanks, I did not notice that.
It's very odd how it will escape double quotes in the server password field but not the serveradminpassword or session name...

**Comment by patrix87** [comment]
@simonghpub Were you able to get the MaxPlayers working ?

**Comment by simonghpub** [comment]
Yeah, I don't get it either with the doublequotes.
About the maxplayers: I see you got it working, nice :)

**Pull request merged**
